---
- hosts: host
  become: true
  vars:
    dockerhub_username: vijaygodson
    dockerhub_password: DecorateSources!12
    docker_image_name: vijaygodson/myapp
    docker_image_tag: latest

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Build docker image
      command: docker build -t vijaygodson/myapp /root/ .

    - name: Login to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
        registry_url: "https://index.docker.io/v1/"

    - name: Push Docker Image
      command: docker push {{ docker_image_name }}:{{ docker_image_tag }}
      changed_when: false

    - name: Create Docker container
      docker_container:
        name: my-container
        image: vijaygodson/myapp:latest
        state: started
        restart_policy: always
        published_ports:
          - "8083:8080"
