---
- hosts: host
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Build docker image
      command: docker build -t myapp /root/.

    - name: Create Docker container
      docker_container:
        name: my-container
        image: myapp:latest
        state: started
        restart_policy: always
        published_ports:
          - "8083:8080"

#    - name: Install Kubernetes
#      include_tasks: kubernetes_installation.yml
